import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { TodoProvider } from "@/lib/contexts/todoContext"
import "./globals.css"
import Header from "@/components/header"
import Footer from "@/components/footer"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TodoProvider>
          <Header />
          {children}
          <Footer />
        </TodoProvider>
      </body>
    </html>
  )
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

